import type { ToolDefinition } from './models/tool-definition.model';

const m = (modes: ToolDefinition['allowedInModes']): ToolDefinition['allowedInModes'] => modes;

/** Read-only internal tool hub — wired via InternalToolHubService + ToolExecutorService. */
export const INTERNAL_READ_TOOLS: ToolDefinition[] = [
	{
		id: 'repository_overview',
		name: 'Repository overview',
		description: 'Project structure summary (read-only)',
		category: 'repository',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'repository_list_files',
		name: 'List repository files',
		description: 'Allowed paths only',
		category: 'repository',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'repository_read_file',
		name: 'Read repository file',
		description: 'Text files under allowlist',
		category: 'repository',
		riskLevel: 'medium',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'repository_search_text',
		name: 'Search repository text',
		description: 'Grep-like search in allowed files',
		category: 'repository',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'docs_list',
		name: 'List documentation',
		description: 'Index docs/ and README files',
		category: 'docs',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'docs_read',
		name: 'Read documentation file',
		description: 'Read a single doc path',
		category: 'docs',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'docs_search',
		name: 'Search documentation',
		description: 'Search within documentation files',
		category: 'docs',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'tickets_list',
		name: 'List tickets',
		description: 'Mock / future Jira provider',
		category: 'tickets',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'tickets_get',
		name: 'Get ticket',
		description: 'Read-only ticket detail',
		category: 'tickets',
		riskLevel: 'medium',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'tickets_search',
		name: 'Search tickets',
		description: 'Search mock ticket backlog',
		category: 'tickets',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'api_catalog_list',
		name: 'List API catalog',
		description: 'Internal API definitions',
		category: 'api',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'api_catalog_get',
		name: 'Get API endpoint',
		description: 'Endpoint detail from catalog',
		category: 'api',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'api_catalog_search',
		name: 'Search API catalog',
		description: 'Filter endpoints',
		category: 'api',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'db_schema_overview',
		name: 'Database schema overview',
		description: 'From documentation only (no live DB)',
		category: 'data',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'db_schema_get_table',
		name: 'Get table schema',
		description: 'Table fragment from schema doc',
		category: 'data',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'db_schema_search',
		name: 'Search schema doc',
		description: 'Text search in schema markdown',
		category: 'data',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'cicd_list_files',
		name: 'List CI/CD files',
		description: 'Allowlisted pipeline configs',
		category: 'devops',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'cicd_read_file',
		name: 'Read CI/CD file',
		description: 'Read yaml/json pipeline file',
		category: 'devops',
		riskLevel: 'medium',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'cicd_analyze',
		name: 'Analyze CI/CD',
		description: 'Heuristic risk notes (read-only)',
		category: 'devops',
		riskLevel: 'medium',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'mcp_list_servers',
		name: 'MCP list servers',
		description: 'Configured MCP servers (read-only)',
		category: 'integration',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'mcp_start_server',
		name: 'MCP start server',
		description: 'Start stdio MCP process (allowlisted command)',
		category: 'integration',
		riskLevel: 'medium',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'mcp_stop_server',
		name: 'MCP stop server',
		description: 'Stop MCP stdio process',
		category: 'integration',
		riskLevel: 'medium',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'mcp_discover_tools',
		name: 'MCP discover tools',
		description: 'List tools from a running MCP server',
		category: 'integration',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'mcp_list_tools',
		name: 'MCP list tools',
		description: 'Cached MCP tool definitions (optionally per server)',
		category: 'integration',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'mcp_call_tool',
		name: 'MCP call tool',
		description: 'Invoke a read-only MCP tool (allowlisted servers)',
		category: 'integration',
		riskLevel: 'medium',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
];
