import type { ToolDefinition } from './models/tool-definition.model';
import { CONNECTOR_TOOLS } from './connector-tools-catalog';
import { INTERNAL_READ_TOOLS } from './internal-tools-catalog';

const m = (modes: ToolDefinition['allowedInModes']): ToolDefinition['allowedInModes'] => modes;

/** Static catalog — permissions refined by ToolPermissionService + agent config. */
export const TOOL_CATALOG: ToolDefinition[] = [
	// Browser
	{
		id: 'browser_open_url',
		name: 'Open URL',
		description: 'Navigate browser to allowed origin (allowlisted URLs only)',
		category: 'browser',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'browser_take_screenshot',
		name: 'Screenshot',
		description: 'Capture viewport screenshot',
		category: 'browser',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'browser_inspect_dom',
		name: 'Inspect DOM',
		description: 'Structured DOM summary',
		category: 'browser',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'browser_click',
		name: 'Click',
		description: 'Click element',
		category: 'browser',
		riskLevel: 'medium',
		enabled: true,
		requiresApproval: true,
		allowedInModes: m(['act']),
	},
	{
		id: 'browser_fill',
		name: 'Fill input',
		description: 'Fill form field',
		category: 'browser',
		riskLevel: 'high',
		enabled: true,
		requiresApproval: true,
		allowedInModes: m(['act']),
	},
	{
		id: 'browser_press',
		name: 'Press key',
		description: 'Press key on selector',
		category: 'browser',
		riskLevel: 'medium',
		enabled: true,
		requiresApproval: true,
		allowedInModes: m(['act']),
	},
	{
		id: 'browser_extract_text',
		name: 'Extract text',
		description: 'Extract visible text sample',
		category: 'browser',
		riskLevel: 'medium',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'browser_close',
		name: 'Close browser',
		description: 'Close Playwright context',
		category: 'browser',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	// Testing
	{
		id: 'test_generate_plan',
		name: 'Generate test plan',
		description: 'Markdown regression matrix',
		category: 'qa',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'test_generate_playwright',
		name: 'Generate Playwright spec',
		description: 'TypeScript spec artifact',
		category: 'qa',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'test_run_smoke_mock',
		name: 'Smoke tests (mock)',
		description: 'Mock smoke results',
		category: 'qa',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'test_run_browser_flow',
		name: 'Browser flow check',
		description: 'Lightweight browser workflow smoke',
		category: 'qa',
		riskLevel: 'medium',
		enabled: true,
		requiresApproval: true,
		allowedInModes: m(['act']),
	},
	// Artifacts
	{
		id: 'artifact_create_markdown',
		name: 'Artifact markdown',
		description: 'Create markdown artifact',
		category: 'docs',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'artifact_create_code',
		name: 'Artifact code',
		description: 'Create code artifact',
		category: 'code',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'artifact_create_test',
		name: 'Artifact test',
		description: 'Create test artifact',
		category: 'qa',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['plan', 'act']),
	},
	{
		id: 'artifact_create_sql',
		name: 'Artifact SQL',
		description: 'Create SQL artifact',
		category: 'data',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'artifact_create_checklist',
		name: 'Artifact checklist',
		description: 'Create checklist artifact',
		category: 'docs',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	// Legacy / general (compat with orchestrator hints)
	{
		id: 'code_generate',
		name: 'Code generate',
		description: 'Generate code',
		category: 'code',
		riskLevel: 'medium',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'api_design',
		name: 'API design',
		description: 'API contract sketch',
		category: 'api',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'dto_generate',
		name: 'DTO generate',
		description: 'DTO stubs',
		category: 'api',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'sql_generate',
		name: 'SQL generate',
		description: 'SQL draft',
		category: 'data',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'database_execute',
		name: 'Execute DB query',
		description: 'Blocked — no execution',
		category: 'data',
		riskLevel: 'critical',
		enabled: false,
		requiresApproval: true,
		allowedInModes: m(['act']),
	},
	{
		id: 'deploy',
		name: 'Deploy',
		description: 'Blocked deployment',
		category: 'devops',
		riskLevel: 'critical',
		enabled: false,
		requiresApproval: true,
		allowedInModes: m(['act']),
	},
	{
		id: 'docs_generate',
		name: 'Docs generate',
		description: 'Documentation',
		category: 'docs',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'release_notes_generate',
		name: 'Release notes',
		description: 'Changelog draft',
		category: 'docs',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'browser_inspect_mock',
		name: 'Browser inspect (mock)',
		description: 'Legacy mock inspect',
		category: 'browser',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'browser_open_mock',
		name: 'Browser open (mock)',
		description: 'Legacy mock open',
		category: 'browser',
		riskLevel: 'medium',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'playwright_generate',
		name: 'Playwright generate',
		description: 'E2E specs',
		category: 'qa',
		riskLevel: 'medium',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['plan', 'act']),
	},
	{
		id: 'cicd_review',
		name: 'CI/CD review',
		description: 'Pipeline review',
		category: 'devops',
		riskLevel: 'medium',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'release_checklist',
		name: 'Release checklist',
		description: 'Deploy checklist',
		category: 'devops',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['plan', 'act']),
	},
	{
		id: 'ticket_summarize',
		name: 'Ticket summarize',
		description: 'Support summary',
		category: 'support',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'reply_draft',
		name: 'Reply draft',
		description: 'Customer reply',
		category: 'support',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'artifact_create_email',
		name: 'Artifact email',
		description: 'Create customer-safe email draft artifact',
		category: 'support',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'artifact_create_yaml',
		name: 'Artifact YAML',
		description: 'Create YAML / pipeline draft artifact',
		category: 'devops',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'browser_profile_list',
		name: 'List browser profiles',
		description: 'List saved browser profiles (metadata only)',
		category: 'browser',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'browser_profile_create',
		name: 'Create browser profile',
		description: 'Create target browser profile for auth capture',
		category: 'browser',
		riskLevel: 'medium',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['plan', 'act']),
	},
	{
		id: 'browser_auth_capture_start',
		name: 'Start auth capture',
		description: 'Open login page for manual session capture',
		category: 'browser',
		riskLevel: 'medium',
		enabled: true,
		requiresApproval: true,
		allowedInModes: m(['act']),
	},
	{
		id: 'browser_auth_capture_complete',
		name: 'Complete auth capture',
		description: 'Save storage state after manual login',
		category: 'browser',
		riskLevel: 'medium',
		enabled: true,
		requiresApproval: true,
		allowedInModes: m(['act']),
	},
	{
		id: 'browser_create_demo_auth_profile',
		name: 'Demo auth profile',
		description: 'Local-only demo login into target app',
		category: 'browser',
		riskLevel: 'medium',
		enabled: true,
		requiresApproval: true,
		allowedInModes: m(['act']),
	},
	{
		id: 'browser_open_authenticated',
		name: 'Open authenticated browser',
		description: 'Navigate with saved browser profile',
		category: 'browser',
		riskLevel: 'medium',
		enabled: true,
		requiresApproval: true,
		allowedInModes: m(['act']),
	},
	{
		id: 'playwright_generate_spec',
		name: 'Generate Playwright spec artifact',
		description: 'Draft Playwright TypeScript (artifact only)',
		category: 'qa',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'playwright_generate_from_template',
		name: 'Generate spec from template',
		description: 'Controlled template scaffold',
		category: 'qa',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'playwright_validate_spec',
		name: 'Validate Playwright spec',
		description: 'Sanitizer for generated spec text',
		category: 'qa',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['plan', 'act']),
	},
	{
		id: 'playwright_run_template',
		name: 'Run Playwright template',
		description: 'Execute allowlisted smoke template',
		category: 'qa',
		riskLevel: 'medium',
		enabled: true,
		requiresApproval: true,
		allowedInModes: m(['act']),
	},
	{
		id: 'playwright_run_validated_spec',
		name: 'Run validated spec',
		description: 'Validate & record spec; execution policy-gated',
		category: 'qa',
		riskLevel: 'high',
		enabled: true,
		requiresApproval: true,
		allowedInModes: m(['act']),
	},
	{
		id: 'playwright_list_runs',
		name: 'List Playwright runs',
		description: 'List test runs for session',
		category: 'qa',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	{
		id: 'playwright_get_run',
		name: 'Get Playwright run',
		description: 'Fetch single test run with cases',
		category: 'qa',
		riskLevel: 'low',
		enabled: true,
		requiresApproval: false,
		allowedInModes: m(['ask', 'plan', 'act']),
	},
	...INTERNAL_READ_TOOLS,
	...CONNECTOR_TOOLS,
];
