/** Canonical permission keys — keep in sync with docs/auth-rbac-architecture.md */
export const PERMISSION_CATALOG: ReadonlyArray<{ key: string; name: string; category: string }> = [
	{ key: 'system.admin', name: 'System admin', category: 'system' },
	{ key: 'system.debug.view', name: 'View runtime debug', category: 'system' },
	{ key: 'system.settings.view', name: 'View settings', category: 'system' },
	{ key: 'agents.view', name: 'View agents', category: 'agents' },
	{ key: 'agents.use', name: 'Use agents', category: 'agents' },
	{ key: 'agents.act', name: 'Act mode / tools', category: 'agents' },
	{ key: 'agents.manage', name: 'Manage agents', category: 'agents' },
	{ key: 'agents.readiness.view', name: 'View readiness', category: 'agents' },
	{ key: 'agents.runtime_debug.view', name: 'Runtime debug', category: 'agents' },
	{ key: 'tools.view', name: 'View tools', category: 'tools' },
	{ key: 'tools.execute.low', name: 'Execute low-risk tools', category: 'tools' },
	{ key: 'tools.execute.medium', name: 'Execute medium-risk tools', category: 'tools' },
	{ key: 'tools.execute.high', name: 'Execute high-risk tools', category: 'tools' },
	{ key: 'tools.approve', name: 'Approve tool runs', category: 'tools' },
	{ key: 'tools.manage', name: 'Manage tool registry', category: 'tools' },
	{ key: 'browser.view', name: 'View browser panel', category: 'browser' },
	{ key: 'browser.open', name: 'Open browser sessions', category: 'browser' },
	{ key: 'browser.inspect', name: 'Inspect DOM', category: 'browser' },
	{ key: 'browser.screenshot', name: 'Screenshots', category: 'browser' },
	{ key: 'browser.action.click', name: 'Browser click', category: 'browser' },
	{ key: 'browser.action.fill', name: 'Browser fill', category: 'browser' },
	{ key: 'browser.manage', name: 'Manage browser worker', category: 'browser' },
	{ key: 'data.rag.view', name: 'View RAG', category: 'data' },
	{ key: 'data.rag.ingest', name: 'Ingest RAG', category: 'data' },
	{ key: 'data.sql.generate', name: 'Generate SQL', category: 'data' },
	{ key: 'data.sql.execute', name: 'Execute SQL', category: 'data' },
	{ key: 'audit.view', name: 'View audit logs', category: 'audit' },
	{ key: 'audit.export', name: 'Export audit', category: 'audit' },
	{ key: 'users.view', name: 'List users', category: 'admin' },
	{ key: 'users.create', name: 'Create users', category: 'admin' },
	{ key: 'users.update', name: 'Update users', category: 'admin' },
	{ key: 'users.disable', name: 'Disable users', category: 'admin' },
	{ key: 'roles.manage', name: 'Manage roles', category: 'admin' },
	{ key: 'permissions.manage', name: 'Manage permissions', category: 'admin' },
];

/** Role key → permission keys (admin uses full catalog). */
export const ROLE_PERMISSION_MAP: Readonly<Record<string, readonly string[]>> = {
	admin: PERMISSION_CATALOG.map((p) => p.key),
	engineering_lead: [
		'system.debug.view',
		'agents.view',
		'agents.use',
		'agents.act',
		'tools.view',
		'tools.manage',
		'tools.execute.low',
		'tools.execute.medium',
		'tools.approve',
		'browser.view',
		'browser.open',
		'browser.inspect',
		'browser.screenshot',
		'browser.action.click',
		'agents.runtime_debug.view',
		'agents.readiness.view',
		'data.sql.generate',
		'audit.view',
	],
	frontend_engineer: [
		'agents.view',
		'agents.use',
		'agents.act',
		'tools.view',
		'tools.execute.low',
		'tools.execute.medium',
		'browser.view',
		'browser.open',
		'browser.inspect',
		'browser.screenshot',
		'data.rag.view',
	],
	backend_engineer: [
		'agents.view',
		'agents.use',
		'agents.act',
		'tools.view',
		'tools.execute.low',
		'tools.execute.medium',
		'data.sql.generate',
		'data.rag.view',
	],
	qa_engineer: [
		'agents.view',
		'agents.use',
		'agents.act',
		'tools.view',
		'tools.execute.low',
		'tools.execute.medium',
		'tools.execute.high',
		'tools.approve',
		'browser.view',
		'browser.open',
		'browser.inspect',
		'browser.screenshot',
		'browser.action.click',
		'browser.action.fill',
		'agents.runtime_debug.view',
		'agents.readiness.view',
	],
	product_manager: [
		'agents.view',
		'agents.use',
		'agents.act',
		'tools.view',
		'tools.execute.low',
		'tools.execute.medium',
		'data.rag.view',
	],
	support_agent: [
		'agents.view',
		'agents.use',
		'agents.act',
		'tools.view',
		'tools.execute.low',
		'tools.execute.medium',
		'data.rag.view',
	],
	data_analyst: ['agents.view', 'agents.use', 'agents.act', 'tools.view', 'tools.execute.low', 'data.sql.generate', 'data.rag.view'],
	devops_engineer: [
		'agents.view',
		'agents.use',
		'agents.act',
		'tools.view',
		'tools.manage',
		'tools.execute.low',
		'tools.execute.medium',
		'tools.approve',
		'agents.readiness.view',
		'audit.view',
	],
	viewer: ['agents.view'],
};

export type DemoAgentAccess = ReadonlyArray<{ email: string; agentSlug: string; accessLevel: string }>;

/** Demo users: email → roleKey + optional agent row overrides handled in seed */
export const DEMO_USERS: ReadonlyArray<{
	email: string;
	password: string;
	name: string;
	roleKey: string;
	agentAccess: ReadonlyArray<{ agentSlug: string; accessLevel: string }>;
}> = [
	{
		email: 'admin@bluemeteor.local',
		password: 'admin123',
		name: 'Admin User',
		roleKey: 'admin',
		agentAccess: [
			{ agentSlug: 'fronto', accessLevel: 'admin' },
			{ agentSlug: 'backo', accessLevel: 'admin' },
			{ agentSlug: 'testo', accessLevel: 'admin' },
			{ agentSlug: 'producto', accessLevel: 'admin' },
			{ agentSlug: 'doco', accessLevel: 'admin' },
			{ agentSlug: 'dato', accessLevel: 'admin' },
			{ agentSlug: 'supporto', accessLevel: 'admin' },
			{ agentSlug: 'devopsy', accessLevel: 'admin' },
		],
	},
	{
		email: 'bluemeteor@bluemeteor.local',
		password: 'bluemeteor',
		name: 'Bluemeteor Demo',
		roleKey: 'admin',
		agentAccess: [
			{ agentSlug: 'fronto', accessLevel: 'admin' },
			{ agentSlug: 'backo', accessLevel: 'admin' },
			{ agentSlug: 'testo', accessLevel: 'admin' },
			{ agentSlug: 'producto', accessLevel: 'admin' },
			{ agentSlug: 'doco', accessLevel: 'admin' },
			{ agentSlug: 'dato', accessLevel: 'admin' },
			{ agentSlug: 'supporto', accessLevel: 'admin' },
			{ agentSlug: 'devopsy', accessLevel: 'admin' },
		],
	},
	{
		email: 'qa@bluemeteor.local',
		password: 'qa123',
		name: 'QA Engineer',
		roleKey: 'qa_engineer',
		agentAccess: [{ agentSlug: 'testo', accessLevel: 'act' }],
	},
	{
		email: 'frontend@bluemeteor.local',
		password: 'frontend123',
		name: 'Frontend Engineer',
		roleKey: 'frontend_engineer',
		agentAccess: [{ agentSlug: 'fronto', accessLevel: 'act' }],
	},
	{
		email: 'backend@bluemeteor.local',
		password: 'backend123',
		name: 'Backend Engineer',
		roleKey: 'backend_engineer',
		agentAccess: [{ agentSlug: 'backo', accessLevel: 'act' }],
	},
	{
		email: 'product@bluemeteor.local',
		password: 'product123',
		name: 'Product Manager',
		roleKey: 'product_manager',
		agentAccess: [
			{ agentSlug: 'producto', accessLevel: 'use' },
			{ agentSlug: 'doco', accessLevel: 'use' },
		],
	},
	{
		email: 'support@bluemeteor.local',
		password: 'support123',
		name: 'Support Agent',
		roleKey: 'support_agent',
		agentAccess: [{ agentSlug: 'supporto', accessLevel: 'use' }],
	},
	{
		email: 'data@bluemeteor.local',
		password: 'data123',
		name: 'Data Analyst',
		roleKey: 'data_analyst',
		agentAccess: [{ agentSlug: 'dato', accessLevel: 'act' }],
	},
	{
		email: 'devops@bluemeteor.local',
		password: 'devops123',
		name: 'DevOps Engineer',
		roleKey: 'devops_engineer',
		agentAccess: [{ agentSlug: 'devopsy', accessLevel: 'act' }],
	},
	{
		email: 'viewer@bluemeteor.local',
		password: 'viewer123',
		name: 'Viewer',
		roleKey: 'viewer',
		agentAccess: [
			{ agentSlug: 'fronto', accessLevel: 'view' },
			{ agentSlug: 'testo', accessLevel: 'view' },
		],
	},
];
