import { Injectable } from '@nestjs/common';

import { PrismaService } from '../../database/prisma.service';
import { AgentImprovementBacklogRepository } from '../repositories/agent-improvement-backlog.repository';
import { FeedbackTriageRepository } from '../repositories/feedback-triage.repository';
import { AgentRegressionAnalysisService } from './agent-regression-analysis.service';

const AGENT_SLUGS = ['fronto', 'backo', 'testo', 'producto', 'doco', 'dato', 'supporto', 'devopsy'];

@Injectable()
export class AgentImprovementReportService {
	constructor(
		private readonly prisma: PrismaService,
		private readonly triageRepo: FeedbackTriageRepository,
		private readonly backlogRepo: AgentImprovementBacklogRepository,
		private readonly regression: AgentRegressionAnalysisService,
	) {}

	async generateReport(): Promise<{ markdown: string; data: Record<string, unknown> }> {
		const [
			feedbackCount,
			avgRow,
			triageStats,
			backlogStats,
			allTriage,
			allBacklog,
		] = await Promise.all([
			this.prisma.pilotFeedback.count(),
			this.prisma.pilotFeedback.aggregate({ _avg: { rating: true } }),
			this.triageRepo.countByCategory(),
			this.backlogRepo.countByStatus(),
			this.triageRepo.list(200),
			this.backlogRepo.list(300),
		]);

		const implemented = allBacklog.filter((b) => b.status === 'implemented').length;
		const validated = allBacklog.filter((b) => b.status === 'validated').length;
		const openHigh = allBacklog.filter(
			(b) => ['new', 'accepted', 'in_progress'].includes(b.status) && ['critical', 'high'].includes(b.priority),
		).length;
		const avgRating =
			avgRow._avg.rating != null ? Math.round(avgRow._avg.rating * 100) / 100 : null;

		const topCategories = [...triageStats]
			.sort((a, b) => b._count._all - a._count._all)
			.slice(0, 5)
			.map((c) => `${c.category}: ${c._count._all}`);

		const snapshotLines: string[] = [];
		for (const slug of AGENT_SLUGS) {
			const s = await this.regression.getAgentQualitySnapshot(slug);
			if (s.latestScore != null) {
				const delta =
					s.scoreDelta != null
						? ` (${s.scoreDelta >= 0 ? '+' : ''}${s.scoreDelta})`
						: '';
				snapshotLines.push(`- **${slug}**: ${s.latestScore}%${delta}`);
			}
		}

		const timestamp = new Date().toISOString();

		const markdown = `# Bluemeteor AI Force — Pilot Improvement Report

Generated: ${timestamp}

---

## Summary

| Metric | Value |
|--------|-------|
| Total pilot feedback | ${feedbackCount} |
| Average rating | ${avgRating ?? 'N/A'}/5 |
| Triaged issues | ${allTriage.length} |
| Open high-severity issues | ${openHigh} |
| Backlog items | ${allBacklog.length} |
| Implemented improvements | ${implemented} |
| Validated improvements | ${validated} |

---

## Top Issue Categories

${topCategories.length ? topCategories.map((c) => `- ${c}`).join('\n') : '_No triaged issues yet._'}

---

## Agent Evaluation Scores

${snapshotLines.length ? snapshotLines.join('\n') : '_No evaluation runs available yet._'}

---

## Improvement Backlog Status

${backlogStats.map((s) => `- **${s.status}**: ${s._count._all}`).join('\n') || '_No backlog items._'}

---

## Open High-Severity Issues

${
	allTriage
		.filter((t) => ['critical', 'high'].includes(t.severity) && !['resolved', 'wont_fix'].includes(t.status))
		.slice(0, 10)
		.map((t) => `- [${t.severity.toUpperCase()}] **${t.agentSlug}** — ${t.summary}`)
		.join('\n') || '_No open high-severity issues._'
}

---

## Implemented Improvements

${
	allBacklog
		.filter((b) => b.status === 'implemented' || b.status === 'validated')
		.slice(0, 10)
		.map((b) => `- [${b.status.toUpperCase()}] **${b.agentSlug}** — ${b.title}`)
		.join('\n') || '_No improvements implemented yet._'
}

---

## Recommended Next Sprint

${this.buildNextSprintRecommendations(allTriage, allBacklog)}

---

_Report generated by Bluemeteor AI Force Pilot Improvement System._
`;

		return {
			markdown,
			data: {
				generatedAt: timestamp,
				feedbackCount,
				averageRating: avgRating,
				triagedCount: allTriage.length,
				openHighSeverityCount: openHigh,
				backlogCount: allBacklog.length,
				implementedCount: implemented,
				validatedCount: validated,
				topCategories,
				agentSnapshotLines: snapshotLines,
				backlogByStatus: backlogStats,
			},
		};
	}

	private buildNextSprintRecommendations(
		triage: { agentSlug: string; category: string; severity: string }[],
		backlog: { status: string; priority: string; agentSlug: string; title: string }[],
	): string {
		const lines: string[] = [];

		const criticalTriage = triage.filter((t) => t.severity === 'critical');
		if (criticalTriage.length) {
			lines.push(
				`1. **Resolve ${criticalTriage.length} critical feedback issues** — ${criticalTriage.map((t) => t.agentSlug).join(', ')}`,
			);
		}

		const highBacklog = backlog.filter(
			(b) => b.priority === 'high' && ['new', 'accepted'].includes(b.status),
		);
		if (highBacklog.length) {
			lines.push(`2. **Advance ${highBacklog.length} high-priority backlog items** to in-progress`);
		}

		const unvalidated = backlog.filter((b) => b.status === 'implemented');
		if (unvalidated.length) {
			lines.push(`3. **Validate ${unvalidated.length} implemented improvements** via evaluation runs`);
		}

		if (!lines.length) {
			lines.push('No immediate recommendations. Continue monitoring feedback and evaluation scores.');
		}

		return lines.join('\n');
	}
}
